name: "Ship migrations separately"
description: "Fails if migrations are included in the PR alongside other changes"
inputs:
  token:
    description: "The GitHub token"
    default: ${{ github.token }}
    required: true
  migration-directory:
    description: "The migration directory to look for"
    default: "database/migrations"
runs:
  using: "node12"
  main: "dist/index.js"
branding:
  icon: "slash"
  color: "gray-dark"
