name: "Fail on drop"
description: "Fail on drop"
inputs:
  ghToken:
    description: "The github token"
    default: ${{ github.token }}
    required: true
runs:
  using: "node12"
  main: "dist/index.js"
